In [ ]:
# Question 4
import numpy as np

X = np.array([[1, 7], [-8, 6], [3, 1]])
Y = np.array([[0, 4, 6, -8], [1, -3, 5, 7], [11, 13, 9, 9], [-1, 0, 8, 7]])
Z = np.array([[0, 4, 8, 1], [-3, 5, 17, 11]])
A = np.array([[1, 17], [2, 14]])

b = np.array([[19, -11, 13]])
c = np.array([[12], [-11], [10]])
x = np.array([[1], [2], [3]])
y = np.array([[3, 3, 1]])

In [5]:
# 1
ans = x.dot(y.dot(y.T.dot(x.T)))
ans

array([[ 19,  38,  57],
       [ 38,  76, 114],
       [ 57, 114, 171]])

In [6]:
# 2
ans = 3*c - 9
ans

array([[ 27],
       [-42],
       [ 21]])

In [7]:
# 3
ans = np.trace(np.inner(A, A)) * A
ans

array([[ 490, 8330],
       [ 980, 6860]])

In [8]:
# 4
ans = 2*X.dot(Z)
ans

array([[-42,  78, 254, 156],
       [-36,  -4,  76, 116],
       [ -6,  34,  82,  28]])

In [12]:
# 5
ans = (b.dot(c)) * A
ans

array([[ 479, 8143],
       [ 958, 6706]])

In [13]:
# 6
ans = b.dot(X.dot(A))
ans

array([[ 306, 3602]])

In [14]:
# 7
ans = c * x 
ans

array([[ 12],
       [-22],
       [ 30]])

In [15]:
# 8
ans = b * y 
ans

array([[ 57, -33,  13]])

In [16]:
# 9
ans = c.dot(x.T)
ans

array([[ 12,  24,  36],
       [-11, -22, -33],
       [ 10,  20,  30]])

In [18]:
# 10
ans = Y.dot(Z.T)
ans

array([[ 56,  34],
       [ 35, 144],
       [133, 284],
       [ 71, 216]])

In [19]:
# Question 5
X = np.array([[2, 3], [9 ,1]])
Y = np.array([[1, 0], [2, 1]])
x = np.array([[1], [3]])
y = np.array([[2], [4]])

In [21]:
# 1st col of X
ans = X[:,0]
print(ans)

[2 9]


In [23]:
# 2nd row of Y
ans = Y[1,:]
print(ans)

[2 1]


In [32]:
# Bottom right of X
x_dim = X.shape[0]
y_dim = X.shape[1]

ans = X[x_dim-1, y_dim-1]
print(ans)

1


In [33]:
# X + Y
ans = X + Y
print(ans)

[[ 3  3]
 [11  2]]


In [34]:
# X + YX
ans = X + Y.dot(X)
print(ans)

[[ 4  6]
 [22  8]]


In [35]:
# Hadamard product of x and y
ans = x * y
print(ans)

[[ 2]
 [12]]


In [37]:
# outer product of x and y
ans = np.outer(x, y)
print(ans)

[[ 2  4]
 [ 6 12]]


In [38]:
# Dot of XY
ans = X.dot(Y)
print(ans)

[[ 8  3]
 [11  1]]


In [39]:
# Inner of XY
ans = np.trace(np.inner(X, Y))
print(ans)

21
