In [9]:
import numpy as np
from numpy import genfromtxt

# Question 1
A = genfromtxt('hw_csv_file/hw_2_A.csv', delimiter=',')
B = genfromtxt('hw_csv_file/hw_2_B.csv', delimiter=',')
C = genfromtxt('hw_csv_file/hw_2_C.csv', delimiter=',')
D = genfromtxt('hw_csv_file/hw_2_D.csv', delimiter=',')
E = genfromtxt('hw_csv_file/hw_2_E.csv', delimiter=',')

x = genfromtxt('hw_csv_file/hw_2_x.csv', delimiter=',')
x = np.reshape(x, (len(x), 1))

y = genfromtxt('hw_csv_file/hw_2_y.csv', delimiter=',')
y = np.reshape(y, (len(y), 1))

z = genfromtxt('hw_csv_file/hw_2_z.csv', delimiter=',')
z = np.reshape(z, (len(z), 1))


In [10]:
# 1
ans = np.max(np.trace(np.inner(A, A)))
print(f'1): {ans}')

1): 292.05


In [11]:
# 2
ans = np.min(np.trace(np.inner(A, B)))
print(f'2): {ans}')

2): 10.449999999999996


In [12]:
# 3
ans = np.sum(np.trace(np.inner(C, D)))
print(f'3): {ans}')

2): -3.49


In [13]:
# 4
ans = np.average((C+D).dot(x))
print(f'4): {ans}')

4): -0.47000000000000014


In [15]:
# 5
ans = np.max(np.trace(np.inner(C.T, D.T))* x)
print(f'5): {ans}')

5): 0.349


In [16]:
# 6
ans = np.min(x.dot(z.T))
print(f'6): {ans}')

6): -3.7199999999999998


In [23]:
# 7
ans = x.dot(z.T)
print(f'7): {ans}')

7): [[-3.72  0.12  0.24]
 [-1.86  0.06  0.12]
 [ 0.   -0.   -0.  ]
 [ 0.31 -0.01 -0.02]
 [-3.72  0.12  0.24]]


In [24]:
# 8
ans = np.sum(A+B-10)
print(f'8): {ans}')

8): -2987.2000000000003


In [25]:
# 9
ans = np.average(A.T.dot(B))
print(f'9): {ans}')

9): -2.774444444444445


In [26]:
# 10
ans = E.T.dot(C.T.dot(D.dot(x)))
print(f'10): {ans}')

10): [[ 8.8684]
 [-4.502 ]
 [-3.0041]
 [-5.5886]]
